region: us-east-1

function_name: keepwarm
handler: service.handler
description: Alternate keepwarm runner for MARC Editor
runtime: python3.8
role: service-role/dlx-dl-role-ggxqj9bh
timeout: 900

# Build options
build:
  source_directories: lib # a comma delimited list of directories in your project root that contains source to package.